"""
Import with: from sni_app.core import ...
API provided by __all__. User should work at the Stack level.

Internal helpers need to be explicitly listed by their private name for import,
but the core functionality shouldn't necessitate this.
"""

from sni_app.core.components.stack import Stack, record_derivation
from sni_app.core.components.workflow import (
    PROCESS_REGISTRY,
    ProcessSpec,
    WorkflowGraph,
    WorkflowNode,
    active_stacks,
    aux_roles_of,
    default_entry_map,
    entry_point_uuids,
    get_process_spec,
    replay_workflow,
    sanitise_params,
    workflow_mode,
)
from sni_app.core.io.image import ALLOWED_EXTENSIONS
from sni_app.core.io.project import Project, load_project, save_project
from sni_app.core.io.stack import (
    discover_and_load,
    discover_stack_dirs,
    export_stacks,
    list_stack_frames,
    resolve_run_meta_array,
    scan_experiment_txts,
)
from sni_app.core.io.workflow import load_workflow, save_workflow, save_workflows
from sni_app.core.process.afga import (
    SPEC_BUILDING_BLOCKS,
    WAVELENGTH_MAX_A,
    WAVELENGTH_MIN_A,
    energies,
    energy_grid,
    process_compound,
    wavelengths,
)
from sni_app.core.process.img_processes import (
    MAX_ROTATION_DEG,
    MAX_SCALE_DEVIATION,
    MAX_TRANSLATION_FRACTION,
    MIN_BLACK_BODIES,
    MIN_INLIER_COUNT,
    MIN_MATCH_COUNT,
    REGISTRATION_MIN_SAMPLES,
)
from sni_app.core.process.roi_processes import (
    BARNS_PER_CM2,
    JANIS_CATALOGUE,
    atten_coefficient,
    clamp_roi_to_stack,
    compute_roi_stats,
    h_cross_section,
    relative_attenuation,
    roi_profile,
    roi_to_mask,
    roi_to_stack,
    stack_wavelengths,
    sum_of_logs_relative_attenuation,
    t_cross_section,
)
from sni_app.core.process.stack_processes import (
    compute_shutter_indices,
    stack_avg,
    stack_bin_frames,
    stack_join,
    stack_normalisation,
    stack_overlap_correction,
    stack_referencing,
    stack_registration,
    stack_sbkg_correction,
    stack_scrubbing,
    stack_slice_acquisitions,
    stack_stitching,
    stack_sum,
)
from sni_app.core.util.logger import default_log_file, log_dir, setup_logger
from sni_app.core.util.run_stats import extract_run_stats, frame_wavelengths
from sni_app.core.util.scrubbing import txt_timestamps

__all__ = [
    "Stack",
    "ALLOWED_EXTENSIONS",
    "record_derivation",
    "discover_and_load",
    "discover_stack_dirs",
    "list_stack_frames",
    "scan_experiment_txts",
    "resolve_run_meta_array",
    "export_stacks",
    "save_project",
    "load_project",
    "Project",
    "save_workflow",
    "save_workflows",
    "load_workflow",
    "stack_overlap_correction",
    "stack_normalisation",
    "stack_scrubbing",
    "stack_sbkg_correction",
    "stack_referencing",
    "stack_registration",
    "stack_slice_acquisitions",
    "stack_bin_frames",
    "stack_avg",
    "stack_sum",
    "stack_join",
    "stack_stitching",
    "compute_shutter_indices",
    "roi_to_stack",
    "relative_attenuation",
    "sum_of_logs_relative_attenuation",
    "atten_coefficient",
    "t_cross_section",
    "h_cross_section",
    "clamp_roi_to_stack",
    "roi_profile",
    "compute_roi_stats",
    "stack_wavelengths",
    "JANIS_CATALOGUE",
    "BARNS_PER_CM2",
    "roi_to_mask",
    "MIN_BLACK_BODIES",
    "MIN_MATCH_COUNT",
    "MIN_INLIER_COUNT",
    "MAX_SCALE_DEVIATION",
    "MAX_ROTATION_DEG",
    "MAX_TRANSLATION_FRACTION",
    "REGISTRATION_MIN_SAMPLES",
    "active_stacks",
    "WorkflowGraph",
    "WorkflowNode",
    "replay_workflow",
    "entry_point_uuids",
    "default_entry_map",
    "PROCESS_REGISTRY",
    "ProcessSpec",
    "get_process_spec",
    "workflow_mode",
    "aux_roles_of",
    "sanitise_params",
    "process_compound",
    "SPEC_BUILDING_BLOCKS",
    "energy_grid",
    "wavelengths",
    "energies",
    "WAVELENGTH_MIN_A",
    "WAVELENGTH_MAX_A",
    "setup_logger",
    "log_dir",
    "default_log_file",
    "extract_run_stats",
    "frame_wavelengths",
    "txt_timestamps",
]
